version: '3'

services:  
  gazebo_docker:
    image: ghcr.io/unl-nimbus-lab/uav_simulator/gazebo_docker
    container_name: gazebo_docker
    stdin_open: true
    tty: true
    network_mode: "host" 
    volumes:
      - ../shared/iq_sim:/home/catkin_ws/src/iq_sim